import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    subtitle: 'Professional Cryptocurrency Trading Platform',
    allRightsReserved: 'All Rights Reserved',
    terms: 'Terms and Services',
    privacy: 'Privacy Policy',
    dashboard: 'Dashboard',
    assets: 'Assets',
    portfolio: 'Portfolio',
    Referral: 'Referral',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    kyc: 'KYC',
    logout: 'Logout',
    selectLanguage: 'Select Language',
    selectCurrency: 'Select Currency',
    login: 'Login',
    register: 'Register',
    home: 'Home',
    swap: 'Swap',
    welcome: 'Welcome',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    email: 'Email',
    password: 'Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    confirmPassword: 'Confirm Password',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    startTrading: 'Start Trading',
    topCryptos: 'Top Cryptocurrencies',
    buy: 'Buy',
    sell: 'Sell',
    amount: 'Amount',
    submit: 'Submit',
    success: 'Success',
    error: 'Error',
    loading: 'Loading...',
    featureNotImplemented: "🚧 This feature isn't implemented yet—but don't worry! You can request it in your next prompt! 🚀",
  },
  es: {
    subtitle: 'Plataforma Profesional de Trading de Criptomonedas',
    allRightsReserved: 'Todos los Derechos Reservados',
    terms: 'Términos y Servicios',
    privacy: 'Política de Privacidad',
    dashboard: 'Panel',
    assets: 'Activos',
    portfolio: 'Portafolio',
    Referral: 'Referencia',
    deposit: 'Depósito',
    withdraw: 'Retirar',
    kyc: 'KYC',
    logout: 'Cerrar Sesión',
    selectLanguage: 'Seleccionar Idioma',
    selectCurrency: 'Seleccionar Moneda',
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    home: 'Inicio',
    swap: 'Intercambiar',
    welcome: 'Bienvenido',
    getStarted: 'Comenzar',
    learnMore: 'Saber Más',
    email: 'Correo',
    password: 'Contraseña',
    firstName: 'Nombre',
    lastName: 'Apellido',
    confirmPassword: 'Confirmar Contraseña',
    signIn: 'Iniciar Sesión',
    signUp: 'Registrarse',
    dontHaveAccount: '¿No tienes cuenta?',
    alreadyHaveAccount: '¿Ya tienes cuenta?',
    startTrading: 'Comenzar Trading',
    topCryptos: 'Top Criptomonedas',
    buy: 'Comprar',
    sell: 'Vender',
    amount: 'Cantidad',
    submit: 'Enviar',
    success: 'Éxito',
    error: 'Error',
    loading: 'Cargando...',
    featureNotImplemented: "🚧 Esta función aún no está implementada, ¡pero no te preocupes! ¡Puedes solicitarla en tu próximo mensaje! 🚀",
  },
  de: {
    subtitle: 'Professionelle Kryptowährungs-Handelsplattform',
    allRightsReserved: 'Alle Rechte vorbehalten',
    terms: 'Geschäftsbedingungen',
    privacy: 'Datenschutz',
    dashboard: 'Dashboard',
    assets: 'Vermögen',
    portfolio: 'Portfolio',
    Referral: 'Empfehlung',
    deposit: 'Einzahlung',
    withdraw: 'Abhebung',
    kyc: 'KYC',
    logout: 'Abmelden',
    selectLanguage: 'Sprache auswählen',
    selectCurrency: 'Währung auswählen',
    login: 'Anmelden',
    register: 'Registrieren',
    home: 'Startseite',
    swap: 'Tauschen',
    welcome: 'Willkommen',
    getStarted: 'Loslegen',
    learnMore: 'Mehr erfahren',
    email: 'E-Mail',
    password: 'Passwort',
    firstName: 'Vorname',
    lastName: 'Nachname',
    confirmPassword: 'Passwort bestätigen',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    dontHaveAccount: 'Haben Sie kein Konto?',
    alreadyHaveAccount: 'Haben Sie bereits ein Konto?',
    startTrading: 'Trading starten',
    topCryptos: 'Top Kryptowährungen',
    buy: 'Kaufen',
    sell: 'Verkaufen',
    amount: 'Betrag',
    submit: 'Senden',
    success: 'Erfolg',
    error: 'Fehler',
    loading: 'Laden...',
    featureNotImplemented: "🚧 Diese Funktion ist noch nicht implementiert – aber keine Sorge! Sie können sie in Ihrer nächsten Anfrage anfordern! 🚀",
  },
  it: {
    subtitle: 'Piattaforma Professionale di Trading Criptovalute',
    allRightsReserved: 'Tutti i Diritti Riservati',
    terms: 'Termini e Servizi',
    privacy: 'Privacy Policy',
    dashboard: 'Dashboard',
    assets: 'Asset',
    portfolio: 'Portfolio',
    Referral: 'Referral',
    deposit: 'Deposito',
    withdraw: 'Prelievo',
    kyc: 'KYC',
    logout: 'Esci',
    selectLanguage: 'Seleziona Lingua',
    selectCurrency: 'Seleziona Valuta',
    login: 'Accedi',
    register: 'Registrati',
    home: 'Home',
    swap: 'Scambia',
    welcome: 'Benvenuto',
    getStarted: 'Inizia',
    learnMore: 'Scopri di più',
    email: 'Email',
    password: 'Password',
    firstName: 'Nome',
    lastName: 'Cognome',
    confirmPassword: 'Conferma Password',
    signIn: 'Accedi',
    signUp: 'Registrati',
    dontHaveAccount: 'Non hai un account?',
    alreadyHaveAccount: 'Hai già un account?',
    startTrading: 'Inizia Trading',
    topCryptos: 'Top Criptovalute',
    buy: 'Compra',
    sell: 'Vendi',
    amount: 'Importo',
    submit: 'Invia',
    cancel: 'Annulla',
    success: 'Successo',
    error: 'Errore',
    loading: 'Caricamento...',
    featureNotImplemented: "🚧 Questa funzionalità non è ancora implementata, ma non preoccuparti! Puoi richiederla nel tuo prossimo prompt! 🚀",
  },
  ru: {
    subtitle: 'Профессиональная платформа торговли криптовалютами',
    allRightsReserved: 'Все права защищены',
    terms: 'Условия и услуги',
    privacy: 'Политика конфиденциальности',
    dashboard: 'Панель',
    assets: 'Активы',
    portfolio: 'Портфель',
    Referral: 'Реферал',
    deposit: 'Депозит',
    withdraw: 'Вывод',
    kyc: 'KYC',
    logout: 'Выйти',
    selectLanguage: 'Выбрать язык',
    selectCurrency: 'Выбрать валюту',
    login: 'Войти',
    register: 'Регистрация',
    home: 'Главная',
    swap: 'Обмен',
    welcome: 'Добро пожаловать',
    getStarted: 'Начать',
    learnMore: 'Узнать больше',
    email: 'Email',
    password: 'Пароль',
    firstName: 'Имя',
    lastName: 'Фамилия',
    confirmPassword: 'Подтвердить пароль',
    signIn: 'Войти',
    signUp: 'Регистрация',
    dontHaveAccount: 'Нет аккаунта?',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    startTrading: 'Начать торговлю',
    topCryptos: 'Топ криптовалют',
    buy: 'Купить',
    sell: 'Продать',
    amount: 'Сумма',
    submit: 'Отправить',
    success: 'Успех',
    error: 'Ошибка',
    loading: 'Загрузка...',
    featureNotImplemented: "🚧 Эта функция еще не реализована, но не волнуйтесь! Вы можете запросить ее в следующем сообщении! 🚀",
  },
  ko: {
    subtitle: '전문 암호화폐 거래 플랫폼',
    allRightsReserved: '모든 권리 보유',
    terms: '이용약관',
    privacy: '개인정보 보호정책',
    dashboard: '대시보드',
    assets: '자산',
    portfolio: '포트폴리오',
    Referral: '추천',
    deposit: '입금',
    withdraw: '출금',
    kyc: 'KYC',
    logout: '로그아웃',
    selectLanguage: '언어 선택',
    selectCurrency: '통화 선택',
    login: '로그인',
    register: '회원가입',
    home: '홈',
    swap: '교환',
    welcome: '환영합니다',
    getStarted: '시작하기',
    learnMore: '더 알아보기',
    email: '이메일',
    password: '비밀번호',
    firstName: '이름',
    lastName: '성',
    confirmPassword: '비밀번호 확인',
    signIn: '로그인',
    signUp: '회원가입',
    dontHaveAccount: '계정이 없으신가요?',
    alreadyHaveAccount: '이미 계정이 있으신가요?',
    startTrading: '거래 시작',
    topCryptos: '상위 암호화폐',
    buy: '구매',
    sell: '판매',
    amount: '금액',
    submit: '제출',
    success: '성공',
    error: '오류',
    loading: '로딩 중...',
    featureNotImplemented: "🚧 이 기능은 아직 구현되지 않았습니다. 걱정하지 마세요! 다음 프롬프트에서 요청할 수 있습니다! 🚀",
  },
  zh: {
    subtitle: '专业加密货币交易平台',
    allRightsReserved: '版权所有',
    terms: '条款和服务',
    privacy: '隐私政策',
    dashboard: '仪表板',
    assets: '资产',
    portfolio: '投资组合',
    Referral: '推荐',
    deposit: '存款',
    withdraw: '提款',
    kyc: 'KYC',
    logout: '登出',
    selectLanguage: '选择语言',
    selectCurrency: '选择货币',
    login: '登录',
    register: '注册',
    home: '首页',
    swap: '交换',
    welcome: '欢迎',
    getStarted: '开始',
    learnMore: '了解更多',
    email: '邮箱',
    password: '密码',
    firstName: '名',
    lastName: '姓',
    confirmPassword: '确认密码',
    signIn: '登录',
    signUp: '注册',
    dontHaveAccount: '没有账户？',
    alreadyHaveAccount: '已有账户？',
    startTrading: '开始交易',
    topCryptos: '热门加密货币',
    buy: '买入',
    sell: '卖出',
    amount: '金额',
    submit: '提交',
    success: '成功',
    error: '错误',
    loading: '加载中...',
    featureNotImplemented: "🚧 此功能尚未实现 - 但别担心！您可以在下一个提示中请求它！🚀",
  },
  ja: {
    subtitle: 'プロフェッショナル暗号通貨取引プラットフォーム',
    allRightsReserved: '全著作権所有',
    terms: '利用規約',
    privacy: 'プライバシーポリシー',
    dashboard: 'ダッシュボード',
    assets: '資産',
    portfolio: 'ポートフォリオ',
    Referral: '紹介',
    deposit: '入金',
    withdraw: '出金',
    kyc: 'KYC',
    logout: 'ログアウト',
    selectLanguage: '言語を選択',
    selectCurrency: '通貨を選択',
    login: 'ログイン',
    register: '登録',
    home: 'ホーム',
    swap: '交換',
    welcome: 'ようこそ',
    getStarted: '始める',
    learnMore: '詳細を見る',
    email: 'メール',
    password: 'パスワード',
    firstName: '名',
    lastName: '姓',
    confirmPassword: 'パスワード確認',
    signIn: 'ログイン',
    signUp: '登録',
    dontHaveAccount: 'アカウントをお持ちでない方',
    alreadyHaveAccount: 'すでにアカウントをお持ちの方',
    startTrading: '取引開始',
    topCryptos: 'トップ暗号通貨',
    buy: '買い',
    sell: '売り',
    amount: '金額',
    submit: '送信',
    success: '成功',
    error: 'エラー',
    loading: '読み込み中...',
    featureNotImplemented: "🚧 この機能はまだ実装されていませんが、ご心配なく！次のプロンプトでリクエストできます！🚀",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};